// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"web-ui/views"
	"web-ui/views/components"
)

func LoginPage(errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = views.BasePublic("Вход в систему", LoginForm(errorMsg)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func LoginForm(errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"row justify-content-center\"><div class=\"col-md-12\"><div class=\"card shadow border-0 rounded-4\"><div class=\"card-body p-4\"><h3 class=\"card-title text-center mb-4\"><i class=\"bi bi-calendar-check\"></i> Учебный портал</h3><form hx-post=\"/login\" hx-target=\"#loginError\" hx-indicator=\"#spinner\" hx-on::after-request=\"if (event.detail.successful) { window.location.href = '/' }\"><div class=\"mb-3\"><label for=\"username\" class=\"form-label\">Логин</label> <input type=\"text\" class=\"form-control\" id=\"username\" name=\"username\" autocomplete=\"username\" required></div><div class=\"mb-3\"><label for=\"password\" class=\"form-label\">Пароль</label> <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" autocomplete=\"current-password\" required></div><div class=\"mb-3 form-check\"><input type=\"checkbox\" class=\"form-check-input\" id=\"rememberLogin\" checked> <label class=\"form-check-label\" for=\"rememberLogin\">Запомнить логин</label></div><div id=\"loginError\" class=\"mb-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errorMsg != "" {
			templ_7745c5c3_Err = components.ErrorAlert(errorMsg).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><button type=\"submit\" class=\"btn btn-primary w-100 py-2\"><span id=\"spinner\" class=\"spinner-border spinner-border-sm me-2 htmx-indicator\" style=\"display: none;\"></span> Войти</button></form></div></div></div></div><script>\n\tdocument.addEventListener('DOMContentLoaded', function () {\n\t\tloadSavedLogin();\n\t});\n\tconst form = document.querySelector('form');\n\tif (form) {\n\t\tform.addEventListener('submit', function () {\n\t\t\tconst remember = document.getElementById('rememberLogin').checked;\n\t\t\tconst username = document.getElementById('username').value;\n\t\t\tif (remember) {\n\t\t\t\trememberLogin(username);\n\t\t\t} else {\n\t\t\t\tlocalStorage.removeItem('saved_login');\n\t\t\t}\n\t\t});\n\t}\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
